import {
  createRecipeCard,
  getRecipeCard,
  listRecipeCards,
  deleteRecipeCard,
  saveRecipe,
  unsaveRecipe,
} from '../../controllers/recipeCard.controller.js';
import Recipe from '../../models/recipe.model.js';
import User from '../../models/user.model.js';

jest.mock('../../models/recipe.model.js');
jest.mock('../../models/user.model.js');

describe('Recipe Card Controller', () => {
  let mockRequest;
  let mockResponse;
  const firebaseUID = 'test-user-123';
  const userMongoId = 'mongo-user-id-abc';
  const mockUser = { _id: userMongoId, firebaseUID };

  beforeEach(() => {
    mockRequest = {
      user: { uid: firebaseUID },
      body: {},
      params: {},
    };
    mockResponse = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn(),
    };
    User.findOne.mockResolvedValue(mockUser);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('createRecipeCard', () => {
    it('should create a recipe and return 201', async () => {
      mockRequest.body = { recipeTitle: 'Test Recipe' };
      const savedRecipe = { ...mockRequest.body, generatedBy: userMongoId };
      Recipe.prototype.save = jest.fn().mockResolvedValue(savedRecipe);

      await createRecipeCard(mockRequest, mockResponse);

      expect(User.findOne).toHaveBeenCalledWith({ firebaseUID });
      expect(Recipe.prototype.save).toHaveBeenCalled();
      expect(mockResponse.status).toHaveBeenCalledWith(201);
      expect(mockResponse.json).toHaveBeenCalledWith(expect.objectContaining({ data: savedRecipe }));
    });
  });

  describe('getRecipeCard', () => {
    it('should return a recipe if found and user is authorized', async () => {
      const recipe = { _id: 'recipe1', generatedBy: userMongoId };
      mockRequest.params.id = 'recipe1';
      Recipe.findById.mockResolvedValue(recipe);

      await getRecipeCard(mockRequest, mockResponse);

      expect(Recipe.findById).toHaveBeenCalledWith('recipe1');
      expect(mockResponse.status).toHaveBeenCalledWith(200);
      expect(mockResponse.json).toHaveBeenCalledWith({ success: true, data: recipe });
    });

    it('should return 403 if user is not authorized', async () => {
      const recipe = { _id: 'recipe1', generatedBy: 'another-user-id' };
      mockRequest.params.id = 'recipe1';
      Recipe.findById.mockResolvedValue(recipe);
      await getRecipeCard(mockRequest, mockResponse);
      expect(mockResponse.status).toHaveBeenCalledWith(403);
    });
  });

  describe('listRecipeCards', () => {
    it('should return a list of recipes generated by the user', async () => {
      const recipes = [{ _id: 'recipe1', generatedBy: userMongoId }];
      Recipe.find.mockResolvedValue(recipes);

      await listRecipeCards(mockRequest, mockResponse);

      expect(Recipe.find).toHaveBeenCalledWith({ generatedBy: userMongoId });
      expect(mockResponse.status).toHaveBeenCalledWith(200);
      expect(mockResponse.json).toHaveBeenCalledWith({ success: true, count: 1, data: recipes });
    });
  });

  describe('deleteRecipeCard', () => {
    it('should delete a recipe if found and user is authorized', async () => {
      const recipe = { _id: 'recipe1', generatedBy: userMongoId, deleteOne: jest.fn().mockResolvedValue(true) };
      mockRequest.params.id = 'recipe1';
      Recipe.findById.mockResolvedValue(recipe);

      await deleteRecipeCard(mockRequest, mockResponse);

      expect(recipe.deleteOne).toHaveBeenCalled();
      expect(mockResponse.status).toHaveBeenCalledWith(200);
    });
  });

  describe('saveRecipe', () => {
    it('should save a recipe for the user and return 200', async () => {
      mockRequest.params.id = 'recipeToSave';
      User.updateOne = jest.fn().mockResolvedValue({ nModified: 1 });
      Recipe.updateOne = jest.fn().mockResolvedValue({ nModified: 1 });

      await saveRecipe(mockRequest, mockResponse);

      expect(User.updateOne).toHaveBeenCalledWith({ _id: userMongoId }, { $addToSet: { savedRecipes: 'recipeToSave' } });
      expect(Recipe.updateOne).toHaveBeenCalledWith({ _id: 'recipeToSave' }, { $addToSet: { savedBy: userMongoId } });
      expect(mockResponse.status).toHaveBeenCalledWith(200);
      expect(mockResponse.json).toHaveBeenCalledWith({ success: true, message: 'Recipe saved successfully.' });
    });
  });

  describe('unsaveRecipe', () => {
    it('should unsave a recipe for the user and return 200', async () => {
      mockRequest.params.id = 'recipeToUnsave';
      User.updateOne = jest.fn().mockResolvedValue({ nModified: 1 });
      Recipe.updateOne = jest.fn().mockResolvedValue({ nModified: 1 });

      await unsaveRecipe(mockRequest, mockResponse);

      expect(User.updateOne).toHaveBeenCalledWith({ _id: userMongoId }, { $pull: { savedRecipes: 'recipeToUnsave' } });
      expect(Recipe.updateOne).toHaveBeenCalledWith({ _id: 'recipeToUnsave' }, { $pull: { savedBy: userMongoId } });
      expect(mockResponse.status).toHaveBeenCalledWith(200);
      expect(mockResponse.json).toHaveBeenCalledWith({ success: true, message: 'Recipe unsaved successfully.' });
    });
  });
});
